apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: k8s-device-plugin-demo-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: k8s-device-plugin-demo
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: k8s-device-plugin-demo
    spec:
      priorityClassName: "system-node-critical"
      containers:
        - image: k8s-device-plugin-demo:0.0.1
          name: k8s-device-plugin-demo-ctr
          volumeMounts:
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
